/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/cjlnqRkohTG
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Breadcrumb, BreadcrumbList, BreadcrumbItem, BreadcrumbLink, BreadcrumbSeparator, BreadcrumbPage } from "@/shadcnuicomponents/ui/breadcrumb"
import { Input } from "@/shadcnuicomponents/ui/input"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem } from "@/shadcnuicomponents/ui/dropdown-menu"
import { Button } from "@/shadcnuicomponents/ui/button"
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/shadcnuicomponents/ui/card"
import { Badge } from "@/shadcnuicomponents/ui/badge"
import { Separator } from "@/shadcnuicomponents/ui/separator"
import { Avatar, AvatarImage, AvatarFallback } from "@/shadcnuicomponents/ui/avatar"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/shadcnuicomponents/ui/table"
import { Link } from "react-router-dom"

export function Component() {
  return (
    <div className="flex min-h-screen w-full flex-col bg-muted/40">
      <header className="sticky top-0 z-30 flex h-14 items-center gap-4 border-b bg-background px-4 sm:static sm:h-auto sm:border-0 sm:bg-transparent sm:px-6">
        <Breadcrumb className="hidden md:flex">
          <BreadcrumbList>
            <BreadcrumbItem>
              <BreadcrumbLink asChild>
                <Link to="#">
                  Dashboard
                </Link>
              </BreadcrumbLink>
            </BreadcrumbItem>
            <BreadcrumbSeparator />
            <BreadcrumbItem>
              <BreadcrumbPage>Employee Details</BreadcrumbPage>
            </BreadcrumbItem>
          </BreadcrumbList>
        </Breadcrumb>
        <div className="relative ml-auto flex-1 md:grow-0">
          <div className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
          <Input
            type="search"
            placeholder="Search employees..."
            className="w-full rounded-lg bg-background pl-8 md:w-[200px] lg:w-[336px]"
          />
        </div>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="outline" size="icon" className="overflow-hidden rounded-full">
              <img
                src="/placeholder.svg"
                width={36}
                height={36}
                alt="Avatar"
                className="overflow-hidden rounded-full"
              />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuLabel>My Account</DropdownMenuLabel>
            <DropdownMenuSeparator />
            <DropdownMenuItem>Settings</DropdownMenuItem>
            <DropdownMenuItem>Support</DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem>Logout</DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </header>
      <main className="grid flex-1 items-start gap-4 p-4 sm:px-6 sm:py-0 md:gap-8">
        <Card>
          <CardHeader>
            <CardTitle>Employee Details</CardTitle>
            <CardDescription>View and manage employee information.</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid gap-6">
              <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
                <div className="grid gap-1">
                  <div className="text-sm font-medium">Name</div>
                  <div>John Doe</div>
                </div>
                <div className="grid gap-1">
                  <div className="text-sm font-medium">Email</div>
                  <div>john.doe@example.com</div>
                </div>
                <div className="grid gap-1">
                  <div className="text-sm font-medium">Status</div>
                  <div>
                    <Badge variant="secondary">Active</Badge>
                  </div>
                </div>
                <div className="grid gap-1">
                  <div className="text-sm font-medium">Absences</div>
                  <div>2 days</div>
                </div>
              </div>
              <Separator />
              <div className="grid gap-4">
                <div className="grid gap-1">
                  <div className="text-sm font-medium">Consultants</div>
                  <div>
                    <div className="flex items-center gap-2">
                      <Avatar>
                        <AvatarImage src="/placeholder-user.jpg" />
                        <AvatarFallback>C1</AvatarFallback>
                      </Avatar>
                      <div>Jane Smith</div>
                    </div>
                    <div className="flex items-center gap-2">
                      <Avatar>
                        <AvatarImage src="/placeholder-user.jpg" />
                        <AvatarFallback>C2</AvatarFallback>
                      </Avatar>
                      <div>Michael Johnson</div>
                    </div>
                  </div>
                </div>
                <div className="grid gap-1">
                  <div className="text-sm font-medium">Projects</div>
                  <div>
                    <div className="flex items-center gap-2">
                      <Badge variant="outline">Project A</Badge>
                      <Badge variant="outline">Project B</Badge>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
          <Card>
            <CardHeader>
              <CardTitle>Absences</CardTitle>
              <CardDescription>View employee absences.</CardDescription>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Date</TableHead>
                    <TableHead>Type</TableHead>
                    <TableHead>Duration</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  <TableRow>
                    <TableCell>2023-06-15</TableCell>
                    <TableCell>Sick Leave</TableCell>
                    <TableCell>1 day</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>2023-08-01</TableCell>
                    <TableCell>Vacation</TableCell>
                    <TableCell>5 days</TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Consultants</CardTitle>
              <CardDescription>View employee consultants.</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid gap-4">
                <div className="flex items-center gap-4">
                  <Avatar>
                    <AvatarImage src="/placeholder-user.jpg" />
                    <AvatarFallback>C1</AvatarFallback>
                  </Avatar>
                  <div>
                    <div className="font-medium">Jane Smith</div>
                    <div className="text-sm text-muted-foreground">Consultant</div>
                  </div>
                </div>
                <div className="flex items-center gap-4">
                  <Avatar>
                    <AvatarImage src="/placeholder-user.jpg" />
                    <AvatarFallback>C2</AvatarFallback>
                  </Avatar>
                  <div>
                    <div className="font-medium">Michael Johnson</div>
                    <div className="text-sm text-muted-foreground">Consultant</div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Projects</CardTitle>
              <CardDescription>View employee projects.</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid gap-4">
                <div className="flex items-center gap-4">
                  <Badge variant="outline">Project A</Badge>
                  <div className="text-sm text-muted-foreground">Web Application Development</div>
                </div>
                <div className="flex items-center gap-4">
                  <Badge variant="outline">Project B</Badge>
                  <div className="text-sm text-muted-foreground">Mobile App Development</div>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  )
}
